/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mbanking;

import javax.swing.JDesktopPane;

/**
 *
 * @author Dani
 */
public class H_Awal1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form H_Awal1
     */

    @Override
    public JDesktopPane getDesktopPane() {
        return super.getDesktopPane(); //To change body of generated methods, choose Tools | Templates.
    }
    public H_Awal1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_mbank = new javax.swing.JButton();
        btn_bukarekening = new javax.swing.JButton();
        btn_gantiKode = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_mbank1 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(30, 39, 73));

        jLabel1.setBackground(new java.awt.Color(252, 255, 108));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 255, 108));
        jLabel1.setText("Bank");

        jLabel2.setBackground(new java.awt.Color(252, 255, 108));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mobile");

        btn_mbank.setBackground(new java.awt.Color(30, 39, 73));
        btn_mbank.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        btn_mbank.setForeground(new java.awt.Color(255, 255, 255));
        btn_mbank.setText("x");
        btn_mbank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_mbankMousePressed(evt);
            }
        });
        btn_mbank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mbankActionPerformed(evt);
            }
        });

        btn_bukarekening.setBackground(new java.awt.Color(30, 39, 73));
        btn_bukarekening.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        btn_bukarekening.setForeground(new java.awt.Color(255, 255, 255));
        btn_bukarekening.setText("Buka Rekening Baru");
        btn_bukarekening.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_bukarekeningMousePressed(evt);
            }
        });
        btn_bukarekening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bukarekeningActionPerformed(evt);
            }
        });

        btn_gantiKode.setBackground(new java.awt.Color(30, 39, 73));
        btn_gantiKode.setFont(new java.awt.Font("MS PGothic", 0, 22)); // NOI18N
        btn_gantiKode.setForeground(new java.awt.Color(255, 255, 255));
        btn_gantiKode.setText("Ganti Password User Akses");
        btn_gantiKode.setPreferredSize(new java.awt.Dimension(265, 33));
        btn_gantiKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gantiKodeActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(252, 255, 108));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(252, 255, 108));
        jLabel3.setText("Save your money in here.");

        btn_mbank1.setBackground(new java.awt.Color(30, 39, 73));
        btn_mbank1.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        btn_mbank1.setForeground(new java.awt.Color(255, 255, 255));
        btn_mbank1.setText("Mulai Bank Mobile");
        btn_mbank1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_mbank1MousePressed(evt);
            }
        });
        btn_mbank1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mbank1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_gantiKode, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_bukarekening, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_mbank1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 101, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_mbank, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_mbank)
                .addGap(96, 96, 96)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(btn_mbank1)
                .addGap(18, 18, 18)
                .addComponent(btn_bukarekening, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_gantiKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mbankMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mbankMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_mbankMousePressed

    private void btn_mbankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mbankActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_mbankActionPerformed

    private void btn_bukarekeningMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bukarekeningMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_bukarekeningMousePressed

    private void btn_bukarekeningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bukarekeningActionPerformed
        // TODO add your handling code here:
        H_DaftarRekeningBaru nasabah = new H_DaftarRekeningBaru();
        nasabah.setVisible(true);
        this.getDesktopPane().add(nasabah);
        this.dispose();
        
    }//GEN-LAST:event_btn_bukarekeningActionPerformed

    private void btn_gantiKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gantiKodeActionPerformed
        // TODO add your handling code here:
        H_GantiKode GK = new H_GantiKode();
        GK.setVisible(true);
        this.getDesktopPane().add(GK);
        this.dispose();
    }//GEN-LAST:event_btn_gantiKodeActionPerformed

    private void btn_mbank1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mbank1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_mbank1MousePressed

    private void btn_mbank1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mbank1ActionPerformed
        // TODO add your handling code here:
        H_InputKodeAkses HA = new H_InputKodeAkses();
        HA.setVisible(true);
        this.getDesktopPane().add(HA);
        this.dispose();
    }//GEN-LAST:event_btn_mbank1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bukarekening;
    private javax.swing.JButton btn_gantiKode;
    private javax.swing.JButton btn_mbank;
    private javax.swing.JButton btn_mbank1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
