/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mbanking;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import database.koneksi;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Dani
 */
public class H_Beranda extends javax.swing.JInternalFrame {

    /**
     * Creates new form H_Beranda
     */
    Connection conn = null;
    PreparedStatement pst;
    Object set;
    ResultSet rs;
    @Override
    public JDesktopPane getDesktopPane() {
        return super.getDesktopPane(); //To change body of generated methods, choose Tools | Templates.
    }
    public H_Beranda() {
        this.rs = null;
        this.pst = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jDialog1 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panel_card = new javax.swing.JPanel();
        btn_bukarekening = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btn_bukarekening1 = new javax.swing.JButton();
        btn_cekHistori = new javax.swing.JButton();
        btn_bukarekening4 = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        btn_bukarekening5 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(252, 255, 108));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Bank");

        jLabel2.setBackground(new java.awt.Color(252, 255, 108));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Mobile");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Selamat Datang,");

        label_nama.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        label_nama.setText("Nama User!");

        jPanel1.setBackground(new java.awt.Color(30, 39, 73));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tabungan saya");

        label_uang.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_uang.setForeground(new java.awt.Color(255, 255, 255));
        label_uang.setText("Rp543.123");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nomor Rekening");

        label_norek.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_norek.setForeground(new java.awt.Color(255, 255, 255));
        label_norek.setText("412356798");

        panel_card.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                panel_cardAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout panel_cardLayout = new javax.swing.GroupLayout(panel_card);
        panel_card.setLayout(panel_cardLayout);
        panel_cardLayout.setHorizontalGroup(
            panel_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_card, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_cardLayout.setVerticalGroup(
            panel_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_card, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        label_card.getAccessibleContext().setAccessibleDescription("");

        tipe_kartu.setText("dasda");
        tipe_kartu.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_uang)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_norek)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tipe_kartu)
                        .addContainerGap())
                    .addComponent(panel_card, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tipe_kartu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_uang)
                    .addComponent(panel_card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(label_norek))
                .addContainerGap())
        );

        btn_bukarekening.setBackground(new java.awt.Color(30, 39, 73));
        btn_bukarekening.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        btn_bukarekening.setForeground(new java.awt.Color(255, 255, 255));
        btn_bukarekening.setText("Buka Rekening Baru");
        btn_bukarekening.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_bukarekeningMousePressed(evt);
            }
        });
        btn_bukarekening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bukarekeningActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Yuk mulai dengan Bank Mobile!");

        btn_bukarekening1.setBackground(new java.awt.Color(30, 39, 73));
        btn_bukarekening1.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        btn_bukarekening1.setForeground(new java.awt.Color(255, 255, 255));
        btn_bukarekening1.setText("Transfer");
        btn_bukarekening1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_bukarekening1MousePressed(evt);
            }
        });
        btn_bukarekening1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bukarekening1ActionPerformed(evt);
            }
        });

        btn_cekHistori.setBackground(new java.awt.Color(30, 39, 73));
        btn_cekHistori.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        btn_cekHistori.setForeground(new java.awt.Color(255, 255, 255));
        btn_cekHistori.setText("Histori Transaksi");
        btn_cekHistori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_cekHistoriMousePressed(evt);
            }
        });
        btn_cekHistori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cekHistoriActionPerformed(evt);
            }
        });

        btn_bukarekening4.setBackground(new java.awt.Color(30, 39, 73));
        btn_bukarekening4.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        btn_bukarekening4.setForeground(new java.awt.Color(255, 255, 255));
        btn_bukarekening4.setText("Lebih ...");
        btn_bukarekening4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_bukarekening4MousePressed(evt);
            }
        });
        btn_bukarekening4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bukarekening4ActionPerformed(evt);
            }
        });

        kembali.setBackground(new java.awt.Color(30, 39, 73));
        kembali.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        kembali.setForeground(new java.awt.Color(255, 255, 255));
        kembali.setText("<");
        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kembaliMousePressed(evt);
            }
        });
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        btn_bukarekening5.setBackground(new java.awt.Color(30, 39, 73));
        btn_bukarekening5.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        btn_bukarekening5.setForeground(new java.awt.Color(255, 255, 255));
        btn_bukarekening5.setText("Profile");
        btn_bukarekening5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_bukarekening5MousePressed(evt);
            }
        });
        btn_bukarekening5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bukarekening5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_bukarekening, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_bukarekening1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(btn_cekHistori, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_bukarekening4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_bukarekening5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(label_nama))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_bukarekening, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_bukarekening1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cekHistori, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_bukarekening4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_bukarekening5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_bukarekeningMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bukarekeningMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_bukarekeningMousePressed

    private void btn_bukarekeningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bukarekeningActionPerformed
        // TODO add your handling code here:
        H_DaftarRekeningBaru nasabah = new H_DaftarRekeningBaru();
        nasabah.setVisible(true);
        this.getDesktopPane().add(nasabah);
        this.dispose();

    }//GEN-LAST:event_btn_bukarekeningActionPerformed

    private void btn_bukarekening1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bukarekening1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_bukarekening1MousePressed

    private void btn_bukarekening1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bukarekening1ActionPerformed
        // TODO add your handling code here:
        H_PilihTransfer tf = new H_PilihTransfer();
        tf.setVisible(true);
        this.getDesktopPane().add(tf);
        this.dispose();
    }//GEN-LAST:event_btn_bukarekening1ActionPerformed

    private void btn_cekHistoriMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cekHistoriMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cekHistoriMousePressed

    private void btn_cekHistoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cekHistoriActionPerformed
        // TODO add your handling code here:
        H_Histori hs = new H_Histori();
        hs.setVisible(true);
        this.getDesktopPane().add(hs);
        this.dispose();
    }//GEN-LAST:event_btn_cekHistoriActionPerformed

    private void btn_bukarekening4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bukarekening4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_bukarekening4MousePressed

    private void btn_bukarekening4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bukarekening4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_bukarekening4ActionPerformed

    private void panel_cardAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_panel_cardAncestorAdded
        // TODO add your handling code here:
        //         ImageIcon gambar = new ImageIcon("src/Gambar/anggrek.jpg");
        //         Gambar.setIcon(gambar);
    }//GEN-LAST:event_panel_cardAncestorAdded

    private void kembaliMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliMousePressed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        H_Awal1 A1 = new H_Awal1();
        A1.setVisible(true);
        this.getDesktopPane().add(A1);
        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void btn_bukarekening5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bukarekening5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_bukarekening5MousePressed

    private void btn_bukarekening5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bukarekening5ActionPerformed
        // TODO add your handling code here:
        H_Profile pf = new H_Profile();
        pf.setVisible(true);
        this.getDesktopPane().add(pf);
        this.dispose();
        
        conn = koneksi.getkoneksi();
        
        
    }//GEN-LAST:event_btn_bukarekening5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bukarekening;
    private javax.swing.JButton btn_bukarekening1;
    private javax.swing.JButton btn_bukarekening4;
    private javax.swing.JButton btn_bukarekening5;
    private javax.swing.JButton btn_cekHistori;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JButton kembali;
    public static final javax.swing.JLabel label_card = new javax.swing.JLabel();
    public static final javax.swing.JLabel label_nama = new javax.swing.JLabel();
    public static final javax.swing.JLabel label_norek = new javax.swing.JLabel();
    public static final javax.swing.JLabel label_uang = new javax.swing.JLabel();
    public javax.swing.JPanel panel_card;
    public static final javax.swing.JLabel tipe_kartu = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
