/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mbanking;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import database.koneksi;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Dani
 */
public class H_GantiKode extends javax.swing.JInternalFrame {

    /**
     * Creates new form H_GantiKode
     */
    Connection conn = null;
    PreparedStatement pst;
    Object set;
    ResultSet rs;
    @Override
    public JDesktopPane getDesktopPane() {
        return super.getDesktopPane(); //To change body of generated methods, choose Tools | Templates.
    }
    public H_GantiKode() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_kode1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_kode2 = new javax.swing.JTextField();

        jPanel2.setBackground(new java.awt.Color(48, 52, 63));

        jLabel1.setBackground(new java.awt.Color(128, 237, 153));
        jLabel1.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 255, 108));
        jLabel1.setText("Ubah Kode Akses");

        btn_cancel.setBackground(new java.awt.Color(134, 135, 180));
        btn_cancel.setText("CANCEL");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_simpan.setBackground(new java.awt.Color(134, 135, 180));
        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Masukkan kode akses sebelumnya");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Masukan kode akses terbaru");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_simpan)
                                .addComponent(jLabel3)))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_kode2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txt_kode1)
                            .addComponent(btn_cancel))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_kode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_kode2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan)
                    .addComponent(btn_cancel))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        H_Awal1 H_A1 = new H_Awal1();
        H_A1.setVisible(true);
        this.getDesktopPane().add(H_A1);
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        conn = koneksi.getkoneksi();
        String kode_sblm = txt_kode1.getText();
        String kode_baru = txt_kode2.getText();
        //String sql = "UPDATE `login_akses` SET `kode_akses` = `'"+kode_baru+"'` WHERE `login_akses`.`kode_akses` = '"+kode_sblm+"'";
        int ok = JOptionPane.showConfirmDialog(null,"Apakah anda yakin akan mengganti kode akses","Konfirmasi",JOptionPane.YES_NO_OPTION);
        try{
            String sql = "UPDATE login_akses SET kode_akses = '"+kode_baru+"' WHERE login_akses.kode_akses ='"+kode_sblm+"'";
            PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);
            if(ok==0){
                try{
                    pst.executeUpdate();
                    
                    JOptionPane.showMessageDialog(null, "DATA BERHASIL DI PERBAHARUI");
                    H_Awal1 H_A1 = new H_Awal1();
                    H_A1.setVisible(true);
                    this.getDesktopPane().add(H_A1);
                    this.dispose();
                } catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"DATA TIDAK BERHASIL DI PERBAHARUI" + e);
                }
            }
        }catch(SQLException e){
        }

    }//GEN-LAST:event_btn_simpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_kode1;
    private javax.swing.JTextField txt_kode2;
    // End of variables declaration//GEN-END:variables
}
