/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mbanking;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import database.koneksi;
import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import static mbanking.H_Beranda.*;
import static mbanking.H_Profile.label_card1;
import static mbanking.H_Profile.txt_namaLengkap;
import static mbanking.H_Profile.txt_norek;
import static mbanking.H_Profile.txt_saldo;
import static mbanking.H_TransferAntarBank.label_saldo2;
import static mbanking.H_Transfer.txt_norek1;
import static mbanking.H_Transfer.label_saldo1;
import static mbanking.H_TransferAntarBank.txt_norek2;

/**
 *
 * @author Dani
 */

public class H_InputKodeAkses extends javax.swing.JInternalFrame {

    /**
     * Creates new form H_InputKodeAkses
     */
    Connection conn = null;
    PreparedStatement pst;
    Object set;
    ResultSet rs;
    @Override
    public JDesktopPane getDesktopPane() {
        return super.getDesktopPane(); //To change body of generated methods, choose Tools | Templates.
    }
    public H_InputKodeAkses() {
        this.rs = null;
        this.pst = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(48, 52, 63));

        jLabel1.setBackground(new java.awt.Color(128, 237, 153));
        jLabel1.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 255, 108));
        jLabel1.setText("user akses");

        btn_cancel.setBackground(new java.awt.Color(134, 135, 180));
        btn_cancel.setText("CANCEL");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_login.setBackground(new java.awt.Color(134, 135, 180));
        btn_login.setText("LOGIN");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_cancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_login))
                            .addComponent(txt_kodeakses, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txt_kodeakses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel)
                    .addComponent(btn_login))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        
        conn = koneksi.getkoneksi();
        String sql = "SELECT * FROM login_akses WHERE kode_akses=?";
        try{
            pst = (PreparedStatement)conn.prepareStatement(sql);
            pst.setString(1, txt_kodeakses.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                H_Beranda Beranda = new H_Beranda();
                label_norek.setText(rs.getString(2));
                label_nama.setText(rs.getString(3));
                txt_norek1.setText(rs.getString(2));
                label_uang.setText(rs.getString(5));
                label_saldo2.setText(rs.getString(5));
                label_saldo1.setText(rs.getString(5));
                txt_namaLengkap.setText(rs.getString(3));
                txt_norek.setText(rs.getString(2));
                txt_norek2.setText(rs.getString(2));
                txt_saldo.setText(rs.getString(5));
                tipe_kartu.setText(rs.getString(6));
                if("BLACK".equals(tipe_kartu.getText())){
                    label_card.setIcon(new ImageIcon(new ImageIcon("src/Gambar/black-card.png").getImage().getScaledInstance(240, 170, Image.SCALE_DEFAULT)));
                    label_card1.setIcon(new ImageIcon(new ImageIcon("src/Gambar/black-card.png").getImage().getScaledInstance(240, 170, Image.SCALE_DEFAULT)));
                    
                } else if("GOLD".equals(tipe_kartu.getText())){
                    label_card.setIcon(new ImageIcon(new ImageIcon("src/Gambar/gold-card.png").getImage().getScaledInstance(240, 170, Image.SCALE_DEFAULT)));
                } else{
                    label_card.setIcon(new ImageIcon(new ImageIcon("src/Gambar/silver-card.png").getImage().getScaledInstance(240, 170, Image.SCALE_DEFAULT)));
                }
                Beranda.setVisible(true);
                this.getDesktopPane().add(Beranda);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Kode akses salah!");
                txt_kodeakses.setText("");
            }
        }catch(HeadlessException | SQLException e){
            
        }
        
        
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        H_Awal1 H_A1 = new H_Awal1();
        H_A1.setVisible(true);
        this.getDesktopPane().add(H_A1);
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static final javax.swing.JPasswordField txt_kodeakses = new javax.swing.JPasswordField();
    // End of variables declaration//GEN-END:variables
}
