/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mbanking;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import database.koneksi;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Dani
 */
public class H_Transfer extends javax.swing.JInternalFrame {
    Connection conn = null;
    com.mysql.jdbc.PreparedStatement pst;
    Object set;
    ResultSet rs;
    Statement st;
    @Override
    public JDesktopPane getDesktopPane() {
        return super.getDesktopPane(); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * Creates new form H_Transfer
     */
    public void kurang_saldo(){
        conn = koneksi.getkoneksi();
         String sql1 = "SELECT * FROM nasabah WHERE `nomor_rekening` LIKE '%"+txt_norek1.getText()+"%'";
         try{
         st = (Statement) conn.createStatement();
            rs = st.executeQuery(sql1);
            if(rs.next()){
                String saldo_awal = rs.getString("saldo");
                int saldo_awal1 = Integer.parseInt(saldo_awal);
                int saldo_kirim = Integer.parseInt(txt_saldotf.getText());
                int saldo_terbaru = saldo_awal1  - saldo_kirim;
                Integer.toString(saldo_terbaru);
//                SELECT harga,harga + 50 FROM penjualan WHERE harga=11000;
                st.executeUpdate("UPDATE nasabah SET saldo = '"+saldo_terbaru+"' WHERE nomor_rekening = '"+txt_norek1.getText()+"'");
                st.executeUpdate("UPDATE login_akses SET saldo_awal = '"+saldo_terbaru+"' WHERE nomor_rekening = '"+txt_norek1.getText()+"'");
                JOptionPane.showMessageDialog(null, "TRANSFER BERHASIL");
                cls();
                
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "" + e);
        }
        
    }
    
    public void cls(){
    txt_rektj.setText("");
    txt_namatj.setText("");
    txt_saldotf.setText("");
    txt_pintf.setVisible(false);
    label_input_pin.setVisible(false);
    btn_tf.setVisible(false);
    btn_canceltf.setVisible(false);
    }
    
    public H_Transfer() {
       this.rs = null;
        this.pst = null;
        initComponents();
        txt_pintf.setVisible(false);
        label_input_pin.setVisible(false);
        btn_tf.setVisible(false);
        btn_canceltf.setVisible(false);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_ok = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_namatj = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_saldotf = new javax.swing.JTextField();
        label_input_pin = new javax.swing.JLabel();
        txt_pintf = new javax.swing.JPasswordField();
        btn_tf = new javax.swing.JButton();
        btn_canceltf = new javax.swing.JButton();
        txt_rektj = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel7.setText("jLabel7");

        jPanel2.setBackground(new java.awt.Color(48, 52, 63));

        jLabel1.setBackground(new java.awt.Color(128, 237, 153));
        jLabel1.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 255, 108));
        jLabel1.setText("Transfer antar rekening");

        btn_ok.setBackground(new java.awt.Color(134, 135, 180));
        btn_ok.setText("ok");
        btn_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_okMouseClicked(evt);
            }
        });
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Masukkan Nomor Rekening");

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Nama pemilik");

        txt_namatj.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Saldo anda saat ini Rp.");

        label_saldo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_saldo1.setForeground(new java.awt.Color(204, 204, 204));
        label_saldo1.setText("999.999");

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Masukkan saldo");

        label_input_pin.setForeground(new java.awt.Color(204, 204, 204));
        label_input_pin.setText("Masukkan pin anda");

        btn_tf.setText("Transfer");
        btn_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tfMouseClicked(evt);
            }
        });
        btn_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tfActionPerformed(evt);
            }
        });

        btn_canceltf.setText("Cancel");
        btn_canceltf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_canceltfMouseClicked(evt);
            }
        });

        txt_rektj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rektjActionPerformed(evt);
            }
        });
        txt_rektj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_rektjKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_rektjKeyReleased(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Nomor Rekening anda");

        txt_norek1.setEnabled(false);
        txt_norek1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_norek1ActionPerformed(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_saldo1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(label_input_pin)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_ok)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_tf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_canceltf))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_pintf, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_norek1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_rektj, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_namatj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(txt_saldotf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(label_saldo1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_norek1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_rektj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_namatj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_saldotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ok)
                    .addComponent(jButton1))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_input_pin)
                    .addComponent(txt_pintf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tf)
                    .addComponent(btn_canceltf))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        
    }//GEN-LAST:event_btn_okActionPerformed

    private void btn_okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_okMouseClicked
        // TODO add your handling code here:
        
        int saldotf = Integer.parseInt(txt_saldotf.getText());
        
        if(txt_rektj.getText() == ""){
            JOptionPane.showMessageDialog(null, "NO REK TUJUAN TIDAK BOLEH KOSONG");
        }else if(txt_saldotf.getText() == ""){
            JOptionPane.showMessageDialog(null, "SALDO TIDAK BOLEH KOSONG");
        }else if(saldotf <= 10000){
            JOptionPane.showMessageDialog(null, "MINIMUN TRANSFER 10.000");
        }else if(txt_norek1.getText() == txt_rektj.getText()){
            JOptionPane.showMessageDialog(null, "NOMOR REKENING TUJUAN TIDAK BOLEH SAMA DENGAN REKENING ANDA");
        }else{
            txt_pintf.setVisible(true);
            label_input_pin.setVisible(true);
            btn_tf.setVisible(true);
            btn_canceltf.setVisible(true);
        }
    }//GEN-LAST:event_btn_okMouseClicked

    private void btn_canceltfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_canceltfMouseClicked
        // TODO add your handling code here:
            txt_pintf.setVisible(false);
            label_input_pin.setVisible(false);
            btn_tf.setVisible(false);
            btn_canceltf.setVisible(false);
            txt_rektj.setText("");
            txt_saldotf.setText("");
    }//GEN-LAST:event_btn_canceltfMouseClicked

    private void btn_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tfActionPerformed
        // TODO add your handling code here:
        Date current = new Date();
        SimpleDateFormat frmttgl = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = frmttgl.format(current);
        conn = koneksi.getkoneksi();
        String sql1 = "SELECT * FROM nasabah WHERE `nomor_rekening` LIKE '%"+txt_rektj.getText()+"%'";
        try{
            st = (Statement) conn.createStatement();
            rs = st.executeQuery(sql1);
            
            int pintf = Integer.parseInt(txt_pintf.getText());
            
            if(rs.next() && pintf == rs.getInt(11)){
                String saldo_awal = rs.getString("saldo");
                int saldo_awal1 = Integer.parseInt(saldo_awal);
                int saldo_kirim = Integer.parseInt(txt_saldotf.getText());
                int saldo_terbaru = saldo_awal1  + saldo_kirim;
                String nama = rs.getString("nama_lengkap");
                String ket = "Transfer ke " + nama;
                Integer.toString(saldo_terbaru);
                
                st.executeUpdate("UPDATE nasabah SET saldo = '"+saldo_terbaru+"' WHERE nomor_rekening = '"+txt_rektj.getText()+"'");
                st.executeUpdate("UPDATE login_akses SET saldo_awal = '"+saldo_terbaru+"' WHERE nomor_rekening = '"+txt_rektj.getText()+"'");
                kurang_saldo();
                JOptionPane.showMessageDialog(null, "TRANSFER BERHASIL");
            
                    H_InputKodeAkses H_IKA = new H_InputKodeAkses();
                    H_IKA.setVisible(true);
                    this.getDesktopPane().add(H_IKA);
                    this.dispose();
                    cls();
                    st.execute("INSERT INTO `histori` (`dari_rekening`, `tanggal`, `keterangan`, `jumlah`) VALUES ('"+txt_norek1.getText()+"','"+ tanggal +"','"+ ket +"','"+ saldo_kirim +"')"); 
            }else{
                JOptionPane.showMessageDialog(null, "PIN SALAH!");
            }
         
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "" + e);
        }
    }//GEN-LAST:event_btn_tfActionPerformed

    private void txt_rektjKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rektjKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txt_rektjKeyPressed

    private void txt_norek1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_norek1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_norek1ActionPerformed

    private void txt_rektjKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rektjKeyReleased
        // TODO add your handling code here:
        conn = koneksi.getkoneksi();
        try{
        st = (Statement) conn.createStatement();
        rs = st.executeQuery("SELECT * FROM nasabah WHERE `nomor_rekening` LIKE '%"+txt_rektj.getText()+"%'");
        if(rs.next()){
            txt_namatj.setText(rs.getString(3));
        } else{
            txt_namatj.setText("TIDAK ADA DATA");            
        }
                   
        } catch(SQLException e){
            
        }
    }//GEN-LAST:event_txt_rektjKeyReleased

    private void txt_rektjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rektjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rektjActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
//        conn = koneksi.getkoneksi();
//        String sql = "SELECT * FROM login_akses WHERE kode_akses=?";
//        try{
//            pst = (PreparedStatement)conn.prepareStatement(sql);
//            pst.setString(1, txt_kodeakses.getText());
//            rs = pst.executeQuery();
//            if(rs.next()){
//                H_Beranda Beranda = new H_Beranda();
//                label_norek.setText(rs.getString(2));
//                label_nama.setText(rs.getString(3));
//                txt_norek1.setText(rs.getString(2));
//                label_uang.setText(rs.getString(5));
//                tipe_kartu.setText(rs.getString(6));
//                if("BLACK".equals(tipe_kartu.getText())){
//                    label_card.setIcon(new ImageIcon(new ImageIcon("src/Gambar/black-card.png").getImage().getScaledInstance(240, 170, Image.SCALE_DEFAULT)));
//                    
//                } else if("GOLD".equals(tipe_kartu.getText())){
//                    label_card.setIcon(new ImageIcon(new ImageIcon("src/Gambar/gold-card.png").getImage().getScaledInstance(240, 170, Image.SCALE_DEFAULT)));
//                } else{
//                    label_card.setIcon(new ImageIcon(new ImageIcon("src/Gambar/silver-card.png").getImage().getScaledInstance(240, 170, Image.SCALE_DEFAULT)));
//                }
//                Beranda.setVisible(true);
//                this.getDesktopPane().add(Beranda);
//                this.dispose();
//            }else{
//                JOptionPane.showMessageDialog(null, "Kode akses salah!");
//                txt_kodeakses.setText("");
//            }
//        }catch(HeadlessException | SQLException e){
//            
//        }
        JOptionPane.showMessageDialog(null, "SILAHKAN LOGIN ULANG");
        H_InputKodeAkses H_B = new H_InputKodeAkses();
        H_B.setVisible(true);
        this.getDesktopPane().add(H_B);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_tfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tfMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_tfMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_canceltf;
    private javax.swing.JButton btn_ok;
    private javax.swing.JButton btn_tf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_input_pin;
    public static final javax.swing.JLabel label_saldo1 = new javax.swing.JLabel();
    private javax.swing.JTextField txt_namatj;
    public static final javax.swing.JTextField txt_norek1 = new javax.swing.JTextField();
    private javax.swing.JPasswordField txt_pintf;
    private javax.swing.JTextField txt_rektj;
    private javax.swing.JTextField txt_saldotf;
    // End of variables declaration//GEN-END:variables
}
