/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mbanking;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import database.koneksi;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import static mbanking.H_Transfer.txt_norek1;
/**
 *
 * @author Dani
 */
public final class H_TransferAntarBank extends javax.swing.JInternalFrame {
    Connection conn = null;
    com.mysql.jdbc.PreparedStatement pst;
    Object set;
    ResultSet rs;
    com.mysql.jdbc.Statement st;
    @Override
    public JDesktopPane getDesktopPane() {
        return super.getDesktopPane(); //To change body of generated methods, choose Tools | Templates.
    }
    
    
    // untuk kurangin saldo dari rekening yang mentransfer
     public void kurang_saldo(){
        conn = koneksi.getkoneksi();
         String sql1 = "SELECT * FROM nasabah WHERE `nomor_rekening` LIKE '%"+txt_norek2.getText()+"%'";
         try{
         st = (Statement) conn.createStatement();
            rs = st.executeQuery(sql1);
            if(rs.next()){
                String saldo_awal = rs.getString("saldo");
                int saldo_awal1 = Integer.parseInt(saldo_awal);
                int saldo_kirim = Integer.parseInt(txt_saldotf.getText());
                int saldo_terbaru = saldo_awal1  - saldo_kirim - 7500;
                Integer.toString(saldo_terbaru);
                st.executeUpdate("UPDATE nasabah SET saldo = '"+saldo_terbaru+"' WHERE nomor_rekening = '"+txt_norek2.getText()+"'");
                st.executeUpdate("UPDATE login_akses SET saldo_awal = '"+saldo_terbaru+"' WHERE nomor_rekening = '"+txt_norek2.getText()+"'");
                JOptionPane.showMessageDialog(null, "TRANSFER BERHASIL");
                cls();
                
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "" + e);
        }
        
    }
    
     
     //untuk kosongkan textfield dsb
    public void cls(){
    txt_saldotf.setText("");
    txt_pintf.setVisible(false);
    label_input_pin.setVisible(false);
    btn_tf.setVisible(false);
    btn_canceltf.setVisible(false);
    }
    
    public H_TransferAntarBank() {
        this.rs = null;
        this.pst = null;
        initComponents();
        txt_pintf.setVisible(false);
        label_input_pin.setVisible(false);
        btn_tf.setVisible(false);
        btn_canceltf.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_ok = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_saldotf = new javax.swing.JTextField();
        label_input_pin = new javax.swing.JLabel();
        txt_pintf = new javax.swing.JPasswordField();
        btn_tf = new javax.swing.JButton();
        btn_canceltf = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_namaTujuan = new javax.swing.JTextField();
        txt_rekTujuan = new javax.swing.JTextField();
        txt_namaBank = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(48, 52, 63));

        jLabel1.setBackground(new java.awt.Color(128, 237, 153));
        jLabel1.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 255, 108));
        jLabel1.setText("Transfer antar Bank");

        btn_ok.setBackground(new java.awt.Color(134, 135, 180));
        btn_ok.setText("ok");
        btn_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_okMouseClicked(evt);
            }
        });
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Rekening Tujuan");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Saldo anda saat ini Rp.");

        label_saldo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_saldo2.setForeground(new java.awt.Color(204, 204, 204));
        label_saldo2.setText("999.999");

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Masukkan saldo");

        label_input_pin.setForeground(new java.awt.Color(204, 204, 204));
        label_input_pin.setText("Masukkan pin anda");

        btn_tf.setText("Transfer");
        btn_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tfActionPerformed(evt);
            }
        });

        btn_canceltf.setText("Cancel");
        btn_canceltf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_canceltfMouseClicked(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Nomor Rekening anda");

        txt_norek2.setEnabled(false);
        txt_norek2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_norek2ActionPerformed(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Nama Pemilik");

        txt_namaTujuan.setEnabled(false);

        txt_rekTujuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_rekTujuanKeyReleased(evt);
            }
        });

        txt_namaBank.setEnabled(false);

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Nama Bank");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(310, 310, 310)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_saldo2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(label_input_pin)
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_pintf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btn_tf)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_canceltf))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txt_norek2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_namaTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_rekTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_namaBank, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_saldotf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btn_ok)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1)))))
                        .addGap(121, 121, 121))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(label_saldo2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_norek2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_rekTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_namaTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_namaBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_saldotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ok)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_input_pin)
                    .addComponent(txt_pintf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tf)
                    .addComponent(btn_canceltf))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_okMouseClicked
        // TODO add your handling code here:
        int saldotf = Integer.parseInt(txt_saldotf.getText());
        
        if(txt_rekTujuan.getText() == ""){
            JOptionPane.showMessageDialog(null, "NO REK TUJUAN TIDAK BOLEH KOSONG");
        }else if(txt_saldotf.getText() == ""){
            JOptionPane.showMessageDialog(null, "SALDO TIDAK BOLEH KOSONG");
        }else if(saldotf <= 10000){
            JOptionPane.showMessageDialog(null, "MINIMUN TRANSFER 10.000");
        }else if(txt_norek1.getText() == txt_rekTujuan.getText()){
            JOptionPane.showMessageDialog(null, "NOMOR REKENING TUJUAN TIDAK BOLEH SAMA DENGAN REKENING ANDA");
        }else{
            txt_pintf.setVisible(true);
            label_input_pin.setVisible(true);
            btn_tf.setVisible(true);
            btn_canceltf.setVisible(true);
        }
    }//GEN-LAST:event_btn_okMouseClicked

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed

    }//GEN-LAST:event_btn_okActionPerformed

    private void btn_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tfActionPerformed
        // TODO add your handling code here:
        Date current = new Date();
        SimpleDateFormat frmttgl = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = frmttgl.format(current);
        conn = koneksi.getkoneksi();
        String sql1 = "SELECT * FROM nasabah WHERE `nomor_rekening` LIKE '%"+txt_norek2.getText()+"%'";
        try{
            st = (Statement) conn.createStatement();
            rs = st.executeQuery(sql1);
      
            int pintf = Integer.parseInt(txt_pintf.getText());
            if(rs.next() && pintf == rs.getInt(11)){
                int saldo_kirim = Integer.parseInt(txt_saldotf.getText());
                String nama = rs.getString("nama_lengkap");
                String ket = "Transfer ke " + nama;
                int biaya_admin = 7500;
                pst = (com.mysql.jdbc.PreparedStatement) conn.prepareStatement("INSERT INTO `histori` (`dari_rekening`, `tanggal`, `keterangan`, `jumlah`, `biaya_admin`) VALUES ('"+txt_norek2.getText()+"','"+ tanggal +"','"+ ket +"','"+ saldo_kirim +"','"+ biaya_admin +"')");     
                pst.executeUpdate();
                    kurang_saldo();
                    JOptionPane.showMessageDialog(null, "TRANSFER BERHASIL");
                    cls();
                        H_InputKodeAkses H_IKA = new H_InputKodeAkses();
                        H_IKA.setVisible(true);
                        this.getDesktopPane().add(H_IKA);
                        this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "PIN SALAH!!!");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "" + e);
        }

    }//GEN-LAST:event_btn_tfActionPerformed

    private void btn_canceltfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_canceltfMouseClicked
        // TODO add your handling code here:
        txt_pintf.setVisible(false);
        label_input_pin.setVisible(false);
        btn_tf.setVisible(false);
        btn_canceltf.setVisible(false);
        txt_saldotf.setText("");
    }//GEN-LAST:event_btn_canceltfMouseClicked

    private void txt_norek2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_norek2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_norek2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JOptionPane.showMessageDialog(null, "SILAHKAN LOGIN ULANG");
        H_InputKodeAkses H_B = new H_InputKodeAkses();
        H_B.setVisible(true);
        this.getDesktopPane().add(H_B);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_rekTujuanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rekTujuanKeyReleased
        // TODO add your handling code here:
        conn = koneksi.getkoneksi();
        try{
        st = (Statement) conn.createStatement();
        rs = st.executeQuery("SELECT * FROM antar_bank WHERE `nomor_rekening` LIKE '%"+txt_rekTujuan.getText()+"%'");
        if(rs.next()){
            txt_namaTujuan.setText(rs.getString(2));
            txt_namaBank.setText(rs.getString(3));
        } else{
            txt_namaTujuan.setText("TIDAK ADA DATA");            
        }
                   
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, ""+e);
        }
    }//GEN-LAST:event_txt_rekTujuanKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_canceltf;
    private javax.swing.JButton btn_ok;
    private javax.swing.JButton btn_tf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_input_pin;
    public static final javax.swing.JLabel label_saldo2 = new javax.swing.JLabel();
    private javax.swing.JTextField txt_namaBank;
    private javax.swing.JTextField txt_namaTujuan;
    public static final javax.swing.JTextField txt_norek2 = new javax.swing.JTextField();
    private javax.swing.JPasswordField txt_pintf;
    private javax.swing.JTextField txt_rekTujuan;
    private javax.swing.JTextField txt_saldotf;
    // End of variables declaration//GEN-END:variables
}
